#!/bin/bash

# Script to trancode full bandwidth dumps that includes whatever and
# produce a lower bandwidth version with just one audio track and one
# set of subtitles - burned into the picture.  The result should be
# suitable for bringing on travel and playing via WiFi on your TV (if
# it supports the codec).

# This script requires
# - mediainfo - to see what's in the files
# - HandBreakCLI - to compress it the right way
# - dialog - to ask the user stuff
# - batch (from the "at" package) to batch process movie compression

get_language () {
    # $1   = "line" number
    # "$2" = lines (tag\ntext\ntag\ntext...)

    case $2 in
	'') echo none # Empty list -
	    return;;
    esac

    # Look up the specified tag from the list and return the
    # corresponding text.  Tag is assumed to be numerical.

    # NOTE we look at the tag we don't actually count the numbers
    # 
    # The sed does this:
    # For all lines matching the contents of $1:
    # - Copy the next line into the linebuffer
    # - Remove the embedded newline
    # - Remove leading number and whitespace
    # - Print the content of the linebuffer
    # For all lines: delete eveything
    # SO: Only the line following the matching line is printed.
    line="$( echo "$2" | sed '/^'$1'$/{N;s/\n/ /;s/^[0-9]* //;p}; d' )"
    echo $line
}


select_language () {
    # $1: Dialog question/instuction
    # $2: Multi-word string consisting of "tag" and "text" pairs as described
    #     in the dialog docs. The "text" part can only be one word since
    #     we're a shell script and are not using arrays.

    case $2 in
	'') return 1;;  # Empty list
    esac

    LINES=$( echo "$2" | wc -l )

    case $LINES in
        0)  # None
            return 1;;

	1)  echo "Odd number of languages: $2" >&2
	    exit 1;;

	2)  # Just one.  Find its number.  It should be 1, but I feel paranoid
	    ID=$( echo "$2" | head -1 );;

        *)  # Several, let the user choose
	    clear

	    ID=$( dialog --clear --title "$movie" --menu "$1" 20 30 14 $2 2>&1 >/dev/tty )
	    STATUS=$?
	    case $STATUS in
		255) echo "Dialog error ($1): $ID" >&2
		     exit 255;;
	    esac

	    case $ID in
		'') echo "Canceled" >&2
		    exit 255;;
	    esac
	    ;;
    esac

    return $ID
}


get_audio () {
    # Select audio language
    # A audio track does not necessarily have a language code assigned

    AUDIO=$( mediainfo "$movie" |
              sed '
s/^Audio$/Audio #1/
/^Audio #/,/^$/!d
/^\(Language\|Audio #\|$\)/!d
s/^Audio #/Audio /
s/:/ /
'  | awk '
/Audio /   { N=$2; L="Unknown"; }
/Language/ { L=$2 }
/^$/ { print N"\n"L; }
' )

    case AUDIO in
	'') echo No audio available.  No support for silent movies >&2;
	    exit 1;;
    esac

    # User selects what languages to use
    select_language "Select audio language" "$AUDIO"
    WAID=$?

    # And what language does those numbers correspond to?
    WAUDIO=$(get_language $WAID "$AUDIO")

    AUDIO="--audio $WAID"
}


get_subtitle () {
    # Select subtitle

    # Extract list of subtitle languages
    SUBS="0
None
$( mediainfo "$movie" |
         sed '/^\(Text$\|Text #\)/,/^$/!d;
              s/^Text$/Text #1/;
              /^\(Language\|Text #\)/!d;
              s/^.*[:#][ ]*//; s/ //g;' )"

    select_language "Select subtitle language" "$SUBS"
    WSID=$?

    case $WSID in
	0) WSUB=none;;
	*) WSUB=$(get_language $WSID "$SUBS");;
    esac

    case $WSUB in
	none) echo "No subtitles available"
              SUBTITLE='';;
	*)    SUBTITLE="--subtitle $WSID --subtitle-burn 1"
    esac
}


get_optimization () {
    # List of optimizations
OPT="1
film
2
animation
"

    select_language "Select optimization" "$OPT"
    OPTID=$?
}


get_scaling () {
    WIDTH="$( mediainfo "$movie" |
              sed '/^\(Video$\|Video #\)/,/^$/!d;
                   s/^Video$/Video #1/;
                   /^Width/!d;
                   s/^.*[:#][ ]*//; s/ //g;
                   s/pixels$//;' )"

    LOWER="1
No"

    # Check is width/rows of video stream, but the names of
    # resulutions is lines in the videostream
    case $WIDTH in
	 720) return;;       # SD, no downscaling
	1280) RES="720 HD"   # 1280x720 Broadcast HD
	      LOWER="$LOWER
2
Standard"
	      ;;
	1920|1912) RES="1920 full HD"  # 1920x1080 Full HD
              LOWER="$LOWER
2
720p
3
Standard"
	      ;;
	3840) RES="3840 UHD" # 3840 x 2160p UHD
	      LOWER="$LOWER
2
1080p
3
720p
4
Standard"
	      ;;
	*)    echo "Unrecognized vertical resolution $WIDTH"
              exit 1;;
    esac

    select_language "Video is $RES. Do you want to downscale?" "$LOWER";
    ANSWER=$?

    NEWRES=$(get_language $ANSWER "$LOWER")

    SCALING=""
    SCNAME=""

    case $ANSWER:$NEWRES in
	1:*)  : ;;
	*:Standard)
	    SCALING="--maxWidth=720 --loose-anamorphic --keep-display-aspect"
	    SCNAME="-sd"
	    ;;
	*:720p)
	    SCALING="--maxWidth=1280 --loose-anamorphic --keep-display-aspect"
	    SCNAME="-hd720"
	    ;;
	*:1080p)
	    SCALING="--maxWidth=1920 --loose-anamorphic --keep-display-aspect"
	    SCNAME="-hd1080"
	    ;;
	*)  echo What?
	    exit 1;;
    esac
}


issue_command () {
    OPTN=$(get_language $OPTID "$OPT")

    BN="$(basename "$movie")"
    OUT="${BN%%.*}-$WAUDIO-$WSUB$SCNAME.mkv"
    LOG="${BN%%.*}-$WAUDIO-$WSUB$SCNAME.log"

    # Use $() and cat here to help keep the quoting sane
    CMD="$(cat <<EOF
echo Generating $OUT from $BN
echo Log in $LOG
echo
nice -9 \
    HandBrakeCLI --decomb -v 0 -i '$movie' -o '$OUT' --markers \
    $SCALING --two-pass --turbo \
    -e x264 --x264-tune $OPTN --quality 20 \
    $AUDIO --aencoder lame --ab 256 \
    $SUBTITLE 2> '$LOG'
EOF
)"

    # To check result after a change: --chapters 1

    # --quality 18 was arrived at by looking at different results
    # --quality 20 is HandBrake GUI default quality setting
    # Lame implies mixdown to stereo
    # Used to have --ab 192

    case $DEBUG:$BATCH in
	1:*) echo "$CMD";;
	0:0) eval "$CMD";;
	0:1) echo "$CMD" | batch
             echo Job is queued. Monitor with "at -l" and check mail
	     ;;
    esac
}

BATCH=${SBBATCH:=1}
DEBUG=${SBDEBUG:=0}

case $DEBUG in
    1) set -x
esac

movie="$1"

if [ ! -f "$movie" ] ; then
    echo There does not seem to be any files by that name >&2
    exit 1
fi

get_scaling
get_audio
get_subtitle

get_optimization

clear

issue_command
